package com.ccwu.orbitime

object PinyinBoostData {
    val entries: Map<String, List<String>> = linkedMapOf(
        // High-frequency sentence shortcuts
        "nh" to listOf("你好", "你会", "那好"),
        "nhao" to listOf("你好"),
        "nss" to listOf("你是谁"),
        "nisishei" to listOf("你是谁"),
        "wss" to listOf("我是谁"),
        "woshi" to listOf("我是"),
        "zsm" to listOf("这是什么"),
        "zheshishenme" to listOf("这是什么"),
        "zmb" to listOf("怎么办"),
        "zenmeban" to listOf("怎么办"),
        "smqk" to listOf("什么情况"),
        "shenmeqingkuang" to listOf("什么情况"),
        "hsywt" to listOf("还是有问题"),
        "haishiyouwenti" to listOf("还是有问题"),
        "ywt" to listOf("有问题"),
        "mywt" to listOf("没有问题", "没问题"),
        "mwt" to listOf("没问题"),
        "bdy" to listOf("不对呀", "不对"),
        "buxing" to listOf("不行"),
        "keyi" to listOf("可以"),
        "hd" to listOf("好的"),
        "haode" to listOf("好的"),
        "sd" to listOf("收到"),
        "shoudao" to listOf("收到"),
        "xiexie" to listOf("谢谢"),
        "xx" to listOf("谢谢", "学习", "消息"),
        "dengyixia" to listOf("等一下"),
        "dyx" to listOf("等一下"),
        "shaodeng" to listOf("稍等"),
        "sdyx" to listOf("稍等一下"),
        "wzd" to listOf("我知道"),
        "wozhidao" to listOf("我知道"),
        "wm" to listOf("我们"),
        "nimen" to listOf("你们"),
        "wolaichuli" to listOf("我来处理"),
        "wcl" to listOf("我处理", "我来处理"),
        "wdcl" to listOf("晚点处理"),
        "wdzcl" to listOf("晚点再处理"),
        "wandiandachuli" to listOf("晚点再处理", "晚点处理"),
        "xianzai" to listOf("现在"),
        "jintian" to listOf("今天"),
        "mingtian" to listOf("明天"),
        "zuotian" to listOf("昨天"),
        "yihuir" to listOf("一会儿"),
        "yihui" to listOf("一会"),
        "houxu" to listOf("后续"),
        "xianzy" to listOf("先这样"),
        "jxtl" to listOf("继续讨论"),

        // Work / development shortcuts
        "wj" to listOf("文件", "问题"),
        "wjj" to listOf("文件夹"),
        "wgj" to listOf("文件夹", "无关紧要"),
        "wt" to listOf("问题"),
        "xg" to listOf("修改"),
        "dm" to listOf("代码"),
        "gj" to listOf("构建", "工具"),
        "bd" to listOf("本地", "百度"),
        "sb" to listOf("失败"),
        "cg" to listOf("成功"),
        "rz" to listOf("日志"),
        "cw" to listOf("错误"),
        "qx" to listOf("权限", "取消"),
        "srf" to listOf("输入法"),
        "jqb" to listOf("剪贴板", "剪切板"),
        "fy" to listOf("翻译"),
        "gn" to listOf("功能"),
        "sz" to listOf("设置"),
        "yh" to listOf("优化"),
        "cs" to listOf("测试"),
        "az" to listOf("安装"),
        "xz" to listOf("下载", "选择"),
        "bc" to listOf("保存"),
        "sc" to listOf("删除", "上传"),
        "qk" to listOf("清空"),
        "fz" to listOf("复制"),
        "zt" to listOf("粘贴"),
        "gx" to listOf("更新"),
        "tj" to listOf("提交", "推荐"),
        "hf" to listOf("回复", "恢复"),
        "xf" to listOf("修复"),
        "jc" to listOf("检查", "基础"),
        "ys" to listOf("验收", "意思"),
        "bb" to listOf("版本"),
        "lx" to listOf("联系", "离线"),
        "bdc" to listOf("本地词库"),
        "bdfy" to listOf("本地翻译"),
        "lxfy" to listOf("离线翻译"),
        "tsc" to listOf("提示词"),
        "hxl" to listOf("候选栏"),
        "lj" to listOf("链接", "理解"),
        "ck" to listOf("查看", "窗口"),
        "dz" to listOf("地址", "定制"),
        "ewm" to listOf("二维码"),
        "wd" to listOf("文档", "我的"),
        "nd" to listOf("难点"),
        "zd" to listOf("重点", "知道"),
        "zj" to listOf("总结", "直接"),
        "fx" to listOf("分析", "复习"),
        "jh" to listOf("计划"),
        "rw" to listOf("任务"),
        "mb" to listOf("目标"),
        "lc" to listOf("流程"),
        "jg" to listOf("结果", "结构"),
        "fw" to listOf("范围", "服务"),
        "sj" to listOf("数据", "时间"),
        "mx" to listOf("模型"),
        "ckzx" to listOf("可执行"),
        "zx" to listOf("执行", "最新"),
        "bz" to listOf("步骤", "标准"),
        "xzq" to listOf("选择器"),
        "apk" to listOf("APK"),
        "api" to listOf("API"),
        "github" to listOf("GitHub"),
        "codex" to listOf("Codex"),

        // Full pinyin work phrases
        "wenti" to listOf("问题"),
        "xiugai" to listOf("修改"),
        "wenjian" to listOf("文件"),
        "wenjianjia" to listOf("文件夹"),
        "daima" to listOf("代码"),
        "goujian" to listOf("构建"),
        "shibai" to listOf("失败"),
        "chenggong" to listOf("成功"),
        "rizhi" to listOf("日志"),
        "cuowu" to listOf("错误"),
        "quanxian" to listOf("权限"),
        "shurufa" to listOf("输入法"),
        "jianqieban" to listOf("剪贴板", "剪切板"),
        "fanyi" to listOf("翻译"),
        "gongneng" to listOf("功能"),
        "shezhi" to listOf("设置"),
        "youhua" to listOf("优化"),
        "ceshi" to listOf("测试"),
        "anzhuang" to listOf("安装"),
        "xiazai" to listOf("下载"),
        "baocun" to listOf("保存"),
        "shanchu" to listOf("删除"),
        "qingkong" to listOf("清空"),
        "fuzhi" to listOf("复制"),
        "zhantie" to listOf("粘贴"),
        "tishici" to listOf("提示词"),
        "houxuan" to listOf("候选"),
        "houxuanlan" to listOf("候选栏"),
        "ciku" to listOf("词库"),
        "lianxiang" to listOf("联想"),
        "yonghu" to listOf("用户"),
        "bendi" to listOf("本地"),
        "lixian" to listOf("离线"),
        "yinsi" to listOf("隐私"),
        "jiemian" to listOf("界面"),
        "jiaohu" to listOf("交互"),
        "tiyan" to listOf("体验"),
        "zhuanye" to listOf("专业"),
        "jiejin" to listOf("接近"),

        // Natural phrases for chat
        "yinggaibukai" to listOf("应该不开", "应该不看"),
        "yefangbian" to listOf("也方便"),
        "yifuba" to listOf("衣服吧"),
        "haishiyouwenti" to listOf("还是有问题"),
        "bushichenggongfanyi" to listOf("不是成功翻译"),
        "meiyouzhengqueshiyong" to listOf("没有正确使用"),
        "buhaoyong" to listOf("不好用"),
        "buwanzheng" to listOf("不完整"),
        "jieshenme" to listOf("接什么"),
        "zaishuo" to listOf("再说"),
        "wanquanbuxing" to listOf("完全不行"),
        "keyijieshou" to listOf("可以接受"),
        "zaixiuyixia" to listOf("再修一下"),
        "duojiayixia" to listOf("多加一下"),
        "jiejinzhuanye" to listOf("接近专业"),
        "souxiashuju" to listOf("搜下数据"),
        "buwangluo" to listOf("不联网"),

        // Study/common words
        "xuexi" to listOf("学习"),
        "yingyu" to listOf("英语"),
        "shuxue" to listOf("数学"),
        "cailiao" to listOf("材料"),
        "zhengzhi" to listOf("政治"),
        "fuxi" to listOf("复习"),
        "timu" to listOf("题目"),
        "jiexi" to listOf("解析"),
        "biji" to listOf("笔记"),
        "jihua" to listOf("计划"),
        "kaoshi" to listOf("考试"),
        "zhongdian" to listOf("重点"),
        "nandian" to listOf("难点"),
        "zhishidian" to listOf("知识点"),
        "beisong" to listOf("背诵"),
        "liujing" to listOf("流程"),
        "changnanju" to listOf("长难句"),
        "danci" to listOf("单词"),
        "duanyu" to listOf("短语"),
        "juzi" to listOf("句子")
    )
}
