package com.ccwu.orbitime

object PinyinExpandedData {
    val entries: Map<String, List<String>> = linkedMapOf(
        // 高频社交整句
        "nh" to listOf("你好", "你好吗", "那好"),
        "nhao" to listOf("你好", "你好吗"),
        "nihao" to listOf("你好", "你好吗"),
        "nimenhao" to listOf("你们好"),
        "nisishei" to listOf("你是谁"),
        "nss" to listOf("你是谁"),
        "woshi" to listOf("我是"),
        "wss" to listOf("我是谁"),
        "wsm" to listOf("为什么", "我什么"),
        "sm" to listOf("什么", "说明"),
        "shenme" to listOf("什么"),
        "smqk" to listOf("什么情况"),
        "zsm" to listOf("这是什么"),
        "zheshishenme" to listOf("这是什么"),
        "zmb" to listOf("怎么办"),
        "zenmeban" to listOf("怎么办"),
        "zmcl" to listOf("怎么处理"),
        "zenmechuli" to listOf("怎么处理"),
        "zmyh" to listOf("怎么优化"),
        "zmxg" to listOf("怎么修改"),
        "xianzai" to listOf("现在"),
        "jintian" to listOf("今天"),
        "mingtian" to listOf("明天"),
        "zuotian" to listOf("昨天"),
        "yihui" to listOf("一会", "一会儿"),
        "dengyixia" to listOf("等一下"),
        "dyx" to listOf("等一下"),
        "shaodeng" to listOf("稍等"),
        "sdyx" to listOf("稍等一下"),
        "mashang" to listOf("马上"),
        "denghui" to listOf("等会"),
        "wanshang" to listOf("晚上"),
        "shangwu" to listOf("上午"),
        "xiawu" to listOf("下午"),
        "haode" to listOf("好的"),
        "hd" to listOf("好的"),
        "keyi" to listOf("可以"),
        "ky" to listOf("可以"),
        "buxing" to listOf("不行"),
        "bx" to listOf("不行"),
        "bky" to listOf("不可以"),
        "meiwenti" to listOf("没问题"),
        "mwt" to listOf("没问题"),
        "mywt" to listOf("没有问题", "没问题"),
        "youzi" to listOf("有字"),
        "shoudao" to listOf("收到"),
        "sd" to listOf("收到"),
        "xiexie" to listOf("谢谢"),
        "xx" to listOf("谢谢", "学习", "消息"),
        "bukeqi" to listOf("不客气"),
        "bkhq" to listOf("不客气"),
        "meiguanxi" to listOf("没关系"),
        "mgx" to listOf("没关系"),
        "duibuqi" to listOf("对不起"),
        "dbq" to listOf("对不起"),
        "buhaoyisi" to listOf("不好意思"),
        "bhys" to listOf("不好意思"),
        "wzhdl" to listOf("我知道了"),
        "wzd" to listOf("我知道"),
        "wzdl" to listOf("我知道了"),
        "wqr" to listOf("我确认一下"),
        "wkyx" to listOf("我看一下"),
        "wxyx" to listOf("我想一下"),
        "wzjc" to listOf("我再检查一遍"),
        "wlaichuli" to listOf("我来处理"),
        "wlaicl" to listOf("我来处理"),
        "wcl" to listOf("我处理", "我来处理"),
        "wdcl" to listOf("晚点处理", "我等会处理"),
        "wdzcl" to listOf("晚点再处理"),
        "zswk" to listOf("暂时我看一下"),
        "jtxdzl" to listOf("今天先到这里"),
        "mtjx" to listOf("明天继续"),

        // 你最近测试中的输入法反馈句
        "hsywt" to listOf("还是有问题"),
        "hxywt" to listOf("还是有问题"),
        "hywt" to listOf("还有问题"),
        "sywt" to listOf("是有问题"),
        "myfyjg" to listOf("没有翻译结果"),
        "fyjg" to listOf("翻译结果"),
        "fybd" to listOf("翻译不对"),
        "fybs" to listOf("翻译不是"),
        "bscgfy" to listOf("不是成功翻译"),
        "zsts" to listOf("只是提示词"),
        "bnhcjz" to listOf("不能形成句子"),
        "bnxxqtd" to listOf("不能像其他的"),
        "bnhxqtd" to listOf("不能像其他的"),
        "sjkb" to listOf("数据库不够"),
        "cbbg" to listOf("词表不够", "词库不够"),
        "bty" to listOf("不好用"),
        "jmbd" to listOf("界面不对"),
        "cwbd" to listOf("宠物不对"),
        "cwgnbws" to listOf("宠物功能不完善"),
        "xxyh" to listOf("需要优化"),
        "jxz" to listOf("继续做"),
        "jxwss" to listOf("继续完善"),
        "bwb" to listOf("不完备", "不稳定"),
        "zsq" to listOf("只是前端", "只是轻量"),
        "xyzyyd" to listOf("需要专业一点"),
        "jzzybb" to listOf("接近专业版本"),
        "duojiayixia" to listOf("多加一下"),
        "djyx" to listOf("多加一些"),
        "sxsj" to listOf("搜下数据"),
        "sxyh" to listOf("继续优化"),
        "xcz" to listOf("先重装"),
        "xgj" to listOf("先构建"),
        "xbygj" to listOf("先不要构建"),

        // 开发 / Codex / 构建
        "codex" to listOf("Codex"),
        "github" to listOf("GitHub"),
        "apk" to listOf("APK"),
        "api" to listOf("API"),
        "readme" to listOf("README"),
        "issue" to listOf("Issue"),
        "wjj" to listOf("文件夹"),
        "wgj" to listOf("文件夹", "无关紧要"),
        "wj" to listOf("文件", "问题"),
        "wt" to listOf("问题"),
        "xg" to listOf("修改"),
        "xf" to listOf("修复"),
        "dm" to listOf("代码"),
        "gj" to listOf("构建", "工具"),
        "gjsb" to listOf("构建失败"),
        "gjcg" to listOf("构建成功"),
        "rz" to listOf("日志"),
        "cw" to listOf("错误"),
        "qx" to listOf("权限", "取消"),
        "bb" to listOf("版本"),
        "bbh" to listOf("版本号"),
        "lc" to listOf("流程"),
        "jg" to listOf("结果", "结构"),
        "fw" to listOf("范围", "服务"),
        "zx" to listOf("执行", "最新"),
        "bz" to listOf("步骤", "标准"),
        "ys" to listOf("验收", "意思"),
        "tj" to listOf("提交", "推荐"),
        "gx" to listOf("更新"),
        "jc" to listOf("检查", "基础"),
        "cs" to listOf("测试"),
        "az" to listOf("安装"),
        "xz" to listOf("下载", "选择"),
        "bc" to listOf("保存"),
        "sc" to listOf("删除", "上传"),
        "qk" to listOf("清空"),
        "fz" to listOf("复制"),
        "zt" to listOf("粘贴"),
        "srf" to listOf("输入法"),
        "jqb" to listOf("剪贴板", "剪切板"),
        "fy" to listOf("翻译"),
        "gn" to listOf("功能"),
        "sz" to listOf("设置"),
        "yh" to listOf("优化"),
        "bd" to listOf("本地", "百度"),
        "lx" to listOf("联系", "离线"),
        "bdc" to listOf("本地词库"),
        "bdfy" to listOf("本地翻译"),
        "lxfy" to listOf("离线翻译"),
        "tsc" to listOf("提示词"),
        "hxl" to listOf("候选栏"),
        "xhx" to listOf("候选项"),
        "grck" to listOf("个人词库"),
        "bxxl" to listOf("不学习"),
        "zdxl" to listOf("自动学习"),
        "mhpy" to listOf("模糊拼音"),
        "mhyn" to listOf("模糊音"),
        "lianxiang" to listOf("联想"),
        "jiucuo" to listOf("纠错"),

        // 完整拼音常用词
        "wenjian" to listOf("文件"),
        "wenjianjia" to listOf("文件夹"),
        "wenti" to listOf("问题"),
        "xiugai" to listOf("修改"),
        "xiufu" to listOf("修复"),
        "daima" to listOf("代码"),
        "goujian" to listOf("构建"),
        "shibai" to listOf("失败"),
        "chenggong" to listOf("成功"),
        "rizhi" to listOf("日志"),
        "cuowu" to listOf("错误"),
        "quanxian" to listOf("权限"),
        "shurufa" to listOf("输入法"),
        "jianqieban" to listOf("剪贴板", "剪切板"),
        "fanyi" to listOf("翻译"),
        "gongneng" to listOf("功能"),
        "shezhi" to listOf("设置"),
        "youhua" to listOf("优化"),
        "ceshi" to listOf("测试"),
        "anzhuang" to listOf("安装"),
        "xiazai" to listOf("下载"),
        "baocun" to listOf("保存"),
        "shanchu" to listOf("删除"),
        "qingkong" to listOf("清空"),
        "fuzhi" to listOf("复制"),
        "zhantie" to listOf("粘贴"),
        "xuanze" to listOf("选择"),
        "houxuan" to listOf("候选"),
        "houxuanlan" to listOf("候选栏"),
        "ciku" to listOf("词库"),
        "shuju" to listOf("数据"),
        "shujuku" to listOf("数据库"),
        "yonghu" to listOf("用户"),
        "bendi" to listOf("本地"),
        "lixian" to listOf("离线"),
        "yinsi" to listOf("隐私"),
        "jiemian" to listOf("界面"),
        "jiaohu" to listOf("交互"),
        "tiyan" to listOf("体验"),
        "zhuanye" to listOf("专业"),
        "zhuanyeban" to listOf("专业版"),

        // 学习 / 写作
        "xuexi" to listOf("学习"),
        "yingyu" to listOf("英语"),
        "shuxue" to listOf("数学"),
        "cailiao" to listOf("材料"),
        "zhengzhi" to listOf("政治"),
        "fuxi" to listOf("复习"),
        "timu" to listOf("题目"),
        "jiexi" to listOf("解析"),
        "biji" to listOf("笔记"),
        "jihua" to listOf("计划"),
        "kaoshi" to listOf("考试"),
        "zhongdian" to listOf("重点"),
        "nandian" to listOf("难点"),
        "zhishidian" to listOf("知识点"),
        "beisong" to listOf("背诵"),
        "changnanju" to listOf("长难句"),
        "danci" to listOf("单词"),
        "duanyu" to listOf("短语"),
        "juzi" to listOf("句子"),
        "zhengli" to listOf("整理"),
        "zongjie" to listOf("总结"),
        "tuidai" to listOf("推导"),
        "fangfa" to listOf("方法"),
        "jielun" to listOf("结论"),
        "yuanli" to listOf("原理"),
        "bijiao" to listOf("比较"),
        "fenxi" to listOf("分析"),
        "liucheng" to listOf("流程")
    )

    fun candidatesFor(rawInput: String): List<String> {
        val query = PinyinDictionary.normalize(rawInput)
        if (query.isEmpty()) return emptyList()
        val exact = entries[query].orEmpty()
        val prefix = entries.asSequence()
            .filter { (key, _) -> key != query && key.startsWith(query) }
            .flatMap { (_, values) -> values.asSequence().take(2) }
            .take(24)
            .toList()
        return (exact + prefix).distinct().take(12)
    }
}
